name: deb

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:

    - uses: actions/checkout@v4
      with:
        repository: fatedier/frp
        submodules: true   
    - run: git clone https://github.com/dpkg123/frp-deb
    - run: apt install -y dpkg-dev
    - run: cd frp-deb && bash ./build.sh
    - name: Upload to Artifact 
      uses: actions/upload-artifact@v3
      with: 
       name: "deb"
       path: "out/*.deb"
       
    
